[build]
builder = "RAILPACK"

[deploy]
startCommand = "waitress-serve --url-scheme=https --host=0.0.0.0 --port=$PORT wsgi:application"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
